INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (1, 'John', 50000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (2, 'Peter', 60000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (3, 'Sam', 70000);